version: "3.8"
services:
  livekit-agent:
    image: my-livekit-agent:latest
    restart: always
    env_file:
      - .env.local
    environment:
      LIVEKIT_URL: ${LIVEKIT_URL}
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      
